import pFashion from "@/assets/p-fashion.jpg";
import pLaptop from "@/assets/p-laptop.jpg";
import pCookware from "@/assets/p-cookware.jpg";
import pWatch from "@/assets/p-watch.jpg";
import pBeauty from "@/assets/p-beauty.jpg";
import pShoes from "@/assets/p-shoes.jpg";

export type Product = {
  id: string;
  image: string;
  title: string;
  brand: string;
  price: number;
  mrp: number;
  rating: number;
  reviews: string;
  category: string;
  fashionCategory?: "men" | "women" | "kids";
  subCategory?: string;
  color?: string;
  sizes?: string[];
};

export const categories = [
  "For You",
  "Fashion",
  "Mobiles",
  "Electronics",
  "Beauty",
  "Home",
  "Appliances",
  "Toys & Baby",
  "Grocery",
  "Sports",
  "Furniture",
  "Books",
];

export const products: Product[] = [
  // --- MOBILES ---
  {
    id: "nexon-note-5g",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
    brand: "Nexon",
    title: "Nexon Note 12 5G, 8GB RAM, 128GB, 50MP AI Camera",
    price: 13499,
    mrp: 18999,
    rating: 4.3,
    reviews: "76,431",
    category: "Mobiles",
  },
  {
    id: "nexon-pro-max",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80",
    brand: "Nexon",
    title: "Nexon Pro Max Flagship 5G, 12GB RAM, 256GB Storage",
    price: 39999,
    mrp: 49999,
    rating: 4.6,
    reviews: "22,810",
    category: "Mobiles",
  },
  {
    id: "nexon-flip-5g",
    image: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80",
    brand: "Nexon",
    title: "Nexon Fold & Flip 5G Smartphone with Dual AMOLED Screens",
    price: 69999,
    mrp: 89999,
    rating: 4.5,
    reviews: "9,120",
    category: "Mobiles",
  },

  // --- ELECTRONICS ---
  {
    id: "nexon-air-14",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80",
    brand: "Nexon",
    title: "Nexon Air 14 Thin & Light Laptop, 16GB RAM, 512GB SSD",
    price: 54990,
    mrp: 72990,
    rating: 4.4,
    reviews: "12,480",
    category: "Electronics",
  },
  {
    id: "pulseform-active-2",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
    brand: "Pulseform",
    title: "Pulseform Active 2 Smartwatch with AMOLED Display",
    price: 2199,
    mrp: 5999,
    rating: 4.2,
    reviews: "38,102",
    category: "Electronics",
  },
  {
    id: "pulseform-buds",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
    brand: "Pulseform",
    title: "Pulseform Beat 40 Wireless Earbuds, 40h Playback",
    price: 1099,
    mrp: 3499,
    rating: 4.2,
    reviews: "52,908",
    category: "Electronics",
  },
  {
    id: "nexon-4k-tv",
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80",
    brand: "Nexon",
    title: "Nexon 55-inch Ultra HD 4K Smart LED TV with Dolby Audio",
    price: 32999,
    mrp: 45999,
    rating: 4.5,
    reviews: "14,320",
    category: "Electronics",
  },

  // --- MEN'S FASHION ---
  {
    id: "loomwear-tee-3",
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80",
    brand: "Zara",
    title: "Zara Solid Cotton Round Neck T-Shirt for Men (Pack of 3)",
    price: 649,
    mrp: 1999,
    rating: 4.1,
    reviews: "9,354",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "casual",
    color: "White",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "loomwear-men-jeans",
    image: "https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80",
    brand: "H&M",
    title: "H&M Slim Fit Stretchable Denim Jeans for Men",
    price: 1299,
    mrp: 2999,
    rating: 4.3,
    reviews: "14,810",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "casual",
    color: "Blue",
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "loomwear-men-kurta",
    image: "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=600&q=80",
    brand: "Loomwear",
    title: "Loomwear Silk Blend Festive Nehru Jacket & Kurta Set for Men",
    price: 2499,
    mrp: 4999,
    rating: 4.5,
    reviews: "5,410",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "ethnic",
    color: "Red",
    sizes: ["M", "L", "XL"],
  },
  {
    id: "stridr-men-sports-set",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80",
    brand: "Nike",
    title: "Nike Men's Dry-Fit Gym Training Tracksuit & T-Shirt",
    price: 1599,
    mrp: 3299,
    rating: 4.4,
    reviews: "8,920",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "sports",
    color: "Black",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "loomwear-men-essentials",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80",
    brand: "H&M",
    title: "H&M Premium Pure Cotton Daily Wear Undershirts (Pack of 5)",
    price: 549,
    mrp: 1299,
    rating: 4.2,
    reviews: "11,400",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "essentials",
    color: "Black",
    sizes: ["S", "M", "L"],
  },
  {
    id: "loomwear-boys-tee",
    image: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=600&q=80",
    brand: "Puma",
    title: "Puma Youth Graphic Printed Cotton Hoodie for Boys",
    price: 799,
    mrp: 1799,
    rating: 4.3,
    reviews: "6,210",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "boys",
    color: "Green",
    sizes: ["S", "M", "L"],
  },
  {
    id: "loomwear-leather-belt",
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=600&q=80",
    brand: "Zara",
    title: "Zara Genuine Reversible Leather Belt & Wallet Gift Set",
    price: 899,
    mrp: 2199,
    rating: 4.5,
    reviews: "14,320",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "addons",
    color: "Black",
    sizes: ["M", "L"],
  },
  {
    id: "cleanleaf-men-perfume",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=600&q=80",
    brand: "Zara",
    title: "Zara Royale Long Lasting EDP Perfume for Men 100ml",
    price: 999,
    mrp: 2499,
    rating: 4.4,
    reviews: "18,900",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "fragrance",
    color: "Blue",
    sizes: ["M"],
  },
  {
    id: "stridr-men-shoes",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    brand: "Adidas",
    title: "Adidas Men's Running & Walking Sports Shoes",
    price: 1699,
    mrp: 3499,
    rating: 4.4,
    reviews: "18,400",
    category: "Fashion",
    fashionCategory: "men",
    subCategory: "footwear",
    color: "Red",
    sizes: ["M", "L", "XL"],
  },

  // --- WOMEN'S FASHION ---
  {
    id: "loomwear-women-dress",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    brand: "Zara",
    title: "Zara Printed Cotton A-Line Maxi Dress for Women",
    price: 1199,
    mrp: 2799,
    rating: 4.5,
    reviews: "11,402",
    category: "Fashion",
    fashionCategory: "women",
    subCategory: "western",
    color: "Red",
    sizes: ["S", "M", "L"],
  },
  {
    id: "loomwear-kurta",
    image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80",
    brand: "Loomwear",
    title: "Loomwear Handloom Cotton Straight Kurta for Women",
    price: 899,
    mrp: 2499,
    rating: 4.2,
    reviews: "6,018",
    category: "Fashion",
    fashionCategory: "women",
    subCategory: "ethnic",
    color: "Green",
    sizes: ["M", "L", "XL"],
  },
  {
    id: "loomwear-women-saree",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80",
    brand: "Loomwear",
    title: "Loomwear Silk Blend Woven Saree with Unstitched Blouse",
    price: 1499,
    mrp: 4999,
    rating: 4.3,
    reviews: "19,850",
    category: "Fashion",
    fashionCategory: "women",
    subCategory: "ethnic",
    color: "Red",
    sizes: ["M", "L"],
  },
  {
    id: "loomwear-fusion-tunic",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
    brand: "H&M",
    title: "H&M Indo-Western Asymmetric High-Low Tunic for Women",
    price: 999,
    mrp: 2299,
    rating: 4.3,
    reviews: "7,810",
    category: "Fashion",
    fashionCategory: "women",
    subCategory: "fusion",
    color: "White",
    sizes: ["S", "M", "L"],
  },
  {
    id: "loomwear-women-loungewear",
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=80",
    brand: "H&M",
    title: "H&M Soft Cotton Daily Wear Loungewear Pyjama Set",
    price: 799,
    mrp: 1799,
    rating: 4.4,
    reviews: "12,900",
    category: "Fashion",
    fashionCategory: "women",
    subCategory: "essentials",
    color: "Blue",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "stridr-women-activewear",
    image: "https://images.unsplash.com/photo-1506152983158-b4a74a01c721?auto=format&fit=crop&w=600&q=80",
    brand: "Nike",
    title: "Nike High-Waist Stretch Gym Tights & Sports Bra Set",
    price: 1299,
    mrp: 2999,
    rating: 4.5,
    reviews: "9,420",
    category: "Fashion",
    fashionCategory: "women",
    subCategory: "sportswear",
    color: "Black",
    sizes: ["S", "M", "L"],
  },
  {
    id: "loomwear-girls-top",
    image: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=600&q=80",
    brand: "Zara",
    title: "Zara Casual Denim Jacket & Crop Top Set for Teen Girls",
    price: 1099,
    mrp: 2499,
    rating: 4.2,
    reviews: "5,310",
    category: "Fashion",
    fashionCategory: "women",
    subCategory: "girls",
    color: "Blue",
    sizes: ["S", "M"],
  },
  {
    id: "loomwear-women-heels",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=600&q=80",
    brand: "Zara",
    title: "Zara Elegant Ankle Strap Stiletto Heels for Women",
    price: 1899,
    mrp: 3999,
    rating: 4.4,
    reviews: "7,510",
    category: "Fashion",
    fashionCategory: "women",
    subCategory: "footwear",
    color: "Red",
    sizes: ["S", "M", "L"],
  },

  // --- KIDS' FASHION ---
  {
    id: "loomwear-kids-frock",
    image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=600&q=80",
    brand: "Zara",
    title: "Zara Summer Floral Print Cotton Frock for Kids Girl",
    price: 599,
    mrp: 1499,
    rating: 4.2,
    reviews: "5,412",
    category: "Fashion",
    fashionCategory: "kids",
    subCategory: "girls",
    color: "Red",
    sizes: ["S", "M"],
  },
  {
    id: "loomwear-kids-set",
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=600&q=80",
    brand: "H&M",
    title: "H&M Pure Cotton Printed T-Shirt & Shorts Set for Kids Boys",
    price: 499,
    mrp: 1299,
    rating: 4.4,
    reviews: "7,310",
    category: "Fashion",
    fashionCategory: "kids",
    subCategory: "boys",
    color: "Blue",
    sizes: ["S", "M"],
  },
  {
    id: "babysoft-infant-romper",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80",
    brand: "H&M",
    title: "H&M Soft Organic Cotton Rompers for Infants (Pack of 3)",
    price: 699,
    mrp: 1599,
    rating: 4.6,
    reviews: "11,890",
    category: "Fashion",
    fashionCategory: "kids",
    subCategory: "infants",
    color: "White",
    sizes: ["S"],
  },
  {
    id: "loomwear-kids-hoodie",
    image: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=600&q=80",
    brand: "Puma",
    title: "Puma Fleece Zip-Up Hooded Sweatshirt for Teens",
    price: 799,
    mrp: 1999,
    rating: 4.5,
    reviews: "9,120",
    category: "Fashion",
    fashionCategory: "kids",
    subCategory: "teens",
    color: "Green",
    sizes: ["S", "M", "L"],
  },
  {
    id: "playnest-kids-addon",
    image: "https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&w=600&q=80",
    brand: "Puma",
    title: "Puma Plush Teddy Bear & School Backpack Combo",
    price: 899,
    mrp: 1999,
    rating: 4.4,
    reviews: "8,310",
    category: "Fashion",
    fashionCategory: "kids",
    subCategory: "addons",
    color: "Red",
    sizes: ["S", "M"],
  },

  // --- BEAUTY ---
  {
    id: "cleanleaf-combo",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
    brand: "Cleanleaf",
    title: "Cleanleaf Rice Water Face Wash + Glow Serum Combo",
    price: 449,
    mrp: 799,
    rating: 4.0,
    reviews: "44,209",
    category: "Beauty",
  },
  {
    id: "cleanleaf-shampoo",
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80",
    brand: "Cleanleaf",
    title: "Cleanleaf Onion Hair Shampoo 300ml, No Sulphates",
    price: 329,
    mrp: 599,
    rating: 4.0,
    reviews: "18,776",
    category: "Beauty",
  },

  // --- HOME ---
  {
    id: "ferra-triply-3pc",
    image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=600&q=80",
    brand: "Ferra",
    title: "Ferra Triply Stainless Steel Cookware Set, 3 Pieces",
    price: 2749,
    mrp: 4600,
    rating: 4.5,
    reviews: "5,612",
    category: "Home",
  },

  // --- APPLIANCES ---
  {
    id: "ferra-mixer",
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80",
    brand: "Ferra",
    title: "Ferra 750W Mixer Grinder with 3 Stainless Steel Jars",
    price: 2299,
    mrp: 3999,
    rating: 4.1,
    reviews: "31,204",
    category: "Appliances",
  },

  // --- TOYS & BABY ---
  {
    id: "playnest-blocks",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=600&q=80",
    brand: "Playnest",
    title: "Playnest 120-Piece Building Blocks Set for Kids 3+",
    price: 699,
    mrp: 1499,
    rating: 4.4,
    reviews: "14,203",
    category: "Toys & Baby",
  },

  // --- GROCERY ---
  {
    id: "harvest-dryfruits",
    image: "https://images.unsplash.com/photo-1508061252425-f38321618764?auto=format&fit=crop&w=600&q=80",
    brand: "Harvestly",
    title: "Harvestly Premium Dry Fruits Mix, 500g Resealable Pack",
    price: 549,
    mrp: 999,
    rating: 4.2,
    reviews: "23,776",
    category: "Grocery",
  },

  // --- SPORTS ---
  {
    id: "stridr-glide",
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=600&q=80",
    brand: "Nike",
    title: "Nike Glide Lightweight Running Shoes for Men",
    price: 1499,
    mrp: 3999,
    rating: 4.3,
    reviews: "21,870",
    category: "Sports",
  },

  // --- FURNITURE ---
  {
    id: "woodmark-chair",
    image: "https://images.unsplash.com/photo-1580481072645-022f9a6d1270?auto=format&fit=crop&w=600&q=80",
    brand: "Woodmark",
    title: "Woodmark Ergonomic Mesh Study Chair with Lumbar Support",
    price: 4499,
    mrp: 9999,
    rating: 4.3,
    reviews: "7,318",
    category: "Furniture",
  },

  // --- BOOKS ---
  {
    id: "inkline-atomic",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    brand: "Inkline",
    title: "Inkline Everyday Habits — Paperback Bestseller",
    price: 349,
    mrp: 599,
    rating: 4.6,
    reviews: "1,02,884",
    category: "Books",
  },
];

export const inr = (n: number) => "₹" + n.toLocaleString("en-IN");
