/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CategoryNameRouteImport } from './routes/category.$name'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryNameRoute = CategoryNameRouteImport.update({
  id: '/category/$name',
  path: '/category/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fashion': typeof FashionRoute
  '/wishlist': typeof WishlistRoute
  '/category/$name': typeof CategoryNameRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fashion': typeof FashionRoute
  '/wishlist': typeof WishlistRoute
  '/category/$name': typeof CategoryNameRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fashion': typeof FashionRoute
  '/wishlist': typeof WishlistRoute
  '/category/$name': typeof CategoryNameRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fashion' | '/wishlist' | '/category/$name' | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fashion' | '/wishlist' | '/category/$name' | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/fashion'
    | '/wishlist'
    | '/category/$name'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FashionRoute: typeof FashionRoute
  WishlistRoute: typeof WishlistRoute
  CategoryNameRoute: typeof CategoryNameRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$name': {
      id: '/category/$name'
      path: '/category/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof CategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FashionRoute: FashionRoute,
  WishlistRoute: WishlistRoute,
  CategoryNameRoute: CategoryNameRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
